name: Deploy to sites

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site:
          - name: site1
            secret: DEPLOY_KEY
          - name: site2
            secret: DEPLOY_KEY_2
          - name: site3
            secret: DEPLOY_KEY_3

    steps:
      - name: Checkout core repo
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets[matrix.site.secret] }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone ${{ matrix.site.name }} repo
        run: |
          git clone git@github.com:tommyiaqai/${{ matrix.site.name }}.git ${{ matrix.site.name }}

      - name: Copy files to ${{ matrix.site.name }}
        run: |
          rsync -av --delete ./ ${{ matrix.site.name }}/ \
            --exclude='.git/' \
            --exclude='.github/' \
            --exclude='README.md'

      - name: Commit and push to ${{ matrix.site.name }}
        run: |
          cd ${{ matrix.site.name }}
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy from core on $(date)" || echo "No changes to commit"
          git push origin main
